FROM mcr.microsoft.com/dotnet/aspnet:6.0
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
ENV TZ=Asia/Shanghai
RUN chmod +x /tini && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
WORKDIR /app
VOLUME [ "/rec" ]
COPY ./BililiveRecorder.Cli/bin/docker_out /app
ENTRYPOINT [ "/tini", "--", "dotnet", "/app/BililiveRecorder.Cli.dll" ]
EXPOSE 2356/tcp
CMD [ "run", "--bind", "http://*:2356", "/rec" ]
